

_FIZGIG_PREFS = {"dit": "krea2_raw_dit", "vae": "krea2_vae",
                 "text_encoder": "krea2_text_encoder", "turbo_dit": "krea2_turbo_dit"}


def _sample_prompts(ds: dict) -> str:
    """Preview prompts for --sample_prompts.  Krea 2 takes PLAIN prompts only —
    geometry and seed come from --sample_width/--sample_height/--sample_seed
    (Fizgig docs/CLI.md), so no kohya-style `--w/--h/--d` overrides here.

    Chosen to be the shots a character LoRA is most likely to be WRONG on: a
    close face, a full body (where build drifts first), a 3/4 turn, a profile
    and one hard lighting change.  Same trigger + class the captions use."""
    trig = (ds.get("trigger") or "sks").strip()
    cls = (ds.get("class_token") or "person").strip()
    who = f"{trig} {cls}"
    return "\n".join([
        "# Preview prompts - rendered on the fp8 Turbo each epoch (--turbo_dit).",
        "# One prompt per line; '#' lines are comments. Krea 2 ignores --w/--h/--d here.",
        "# These are deliberately the shots identity fails on first.",
        f"{who}, close-up portrait, neutral expression, soft studio light, plain grey backdrop",
        f"{who}, full body standing, front view, neutral expression, plain studio backdrop",
        f"{who}, waist-up, three-quarter view, slight smile, window light, plain backdrop",
        f"{who}, full body standing, side profile, outdoor daylight, plain background",
        f"{who}, head and shoulders, serious expression, dramatic side light, dark backdrop",
    ]) + "\n"


def _fizgig_runner(ds: dict, n: int) -> str:
    """fizgig_run.py — the whole three-step run, headless.

    Resolves models from Fizgig's own prefs.json rather than hardcoding names:
    fetch_models.py writes ABSOLUTE paths there against the pref keys the GUI
    reads, and it flattens every weight into <fizgig>/models/, so a hardcoded
    `/models/qwen3vl_4b_bf16.safetensors` is wrong twice over (their downloader
    pulls the fp8_scaled variant, and the path is relative to the checkout)."""
    epochs = max(10, min(round(n * 1.2), 40))
    return (_RUNNER_SRC
            .replace("@@PREFS@@", repr(_FIZGIG_PREFS))
            .replace("@@DS_ID@@", repr(ds.get("id")))
            .replace("@@TRIGGER@@", repr((ds.get("trigger") or "sks")))
            .replace("@@EPOCHS@@", str(epochs)))


_RUNNER_SRC = '''"""Run this dataset through Fizgig, headless.  Generated by RBMN Storyboard.

    python fizgig_run.py --fizgig C:/Fizgig
    python fizgig_run.py --fizgig ~/Fizgig --dry-run     # print, run nothing

Point --fizgig at the Fizgig checkout (the folder with lora_trainer_gui.py).
Model paths come from that folder's prefs.json, which Fizgig's own model
downloader fills in - so there is nothing to type.  Override any of them with
--dit / --vae / --text-encoder / --turbo-dit if you keep them elsewhere.

This is not a second-class path: Fizgig's docs/CLI.md says the GUI "is a
front-end that builds these exact commands and runs them as subprocesses".
"""
import argparse
import json
import os
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
PREFS = @@PREFS@@
DS_ID = @@DS_ID@@
TRIGGER = @@TRIGGER@@
EPOCHS = @@EPOCHS@@


def die(msg):
    print("ERROR: " + str(msg), file=sys.stderr)
    raise SystemExit(2)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--fizgig", required=True, help="Fizgig checkout (has lora_trainer_gui.py)")
    ap.add_argument("--python", default=sys.executable, help="python inside Fizgig's venv")
    ap.add_argument("--dry-run", action="store_true")
    ap.add_argument("--skip-cache", action="store_true", help="latents/text already cached")
    ap.add_argument("--quant", choices=("nf4", "int8", "fp8"), default="nf4")
    ap.add_argument("--blocks-to-swap", type=int, default=0)
    ap.add_argument("--epochs", type=int, default=EPOCHS)
    ap.add_argument("--output-dir", default=None)
    for _k in PREFS:
        ap.add_argument("--" + _k.replace("_", "-"), default=None)
    a = ap.parse_args()

    fiz = Path(a.fizgig).expanduser().resolve()
    if not (fiz / "lora_trainer_gui.py").is_file():
        die(str(fiz) + " does not look like a Fizgig checkout (no lora_trainer_gui.py)")
    scripts = fiz / "src" / "fizgig" / "scripts"
    for s in ("krea2_cache_latents.py", "krea2_cache_text.py", "krea2_train.py"):
        if not (scripts / s).is_file():
            die("missing " + s + " - is this Fizgig up to date?")

    # --- the dataset this zip carries -------------------------------------
    imgs = sorted((HERE / "images").glob("*.png"))
    if not imgs:
        die("no images/*.png next to this script - unzip the whole export, keep the layout")
    missing = [p.name for p in imgs if not p.with_suffix(".txt").is_file()]
    if missing:
        die(str(len(missing)) + " image(s) have no caption .txt: " + str(missing[:5]))
    print("dataset: " + str(len(imgs)) + " images, all captioned")

    # --- models, from Fizgig's own prefs.json ------------------------------
    prefs = {}
    pf = fiz / "prefs.json"
    if pf.is_file():
        try:
            prefs = json.loads(pf.read_text("utf-8"))
        except Exception as e:      # a broken prefs.json is not fatal - the flags still work
            print("warning: could not read prefs.json (" + str(e) + ")")
    models = {}
    for flag, key in PREFS.items():
        val = str(getattr(a, flag) or prefs.get(key) or "").strip()
        if val and not os.path.isabs(val):
            val = str((fiz / val).resolve())
        if not val or not os.path.isfile(val):
            die("no file for --" + flag.replace("_", "-") + ".  Either run Fizgig's "
                "Preferences -> 'Download models for me' (it writes prefs.json), or pass "
                "--" + flag.replace("_", "-") + " <path>.  Got: " + (val or "<unset>"))
        models[flag] = val
        print("  " + flag.ljust(13) + " " + val)

    py = a.python
    cfgp = str(HERE / "dataset_fizgig.toml")
    out = a.output_dir or str(fiz / "output_loras" / DS_ID)
    quant = {"nf4": ["--quantize_4bit"], "int8": ["--quant_int8"], "fp8": []}[a.quant]
    if a.quant == "nf4" and a.blocks_to_swap:
        die("NF4 cannot block-swap - the trainer force-zeroes blocks_to_swap under 4-bit. "
            "Use --quant fp8 with --blocks-to-swap, or NF4 with none.")
    swap = ["--blocks_to_swap", str(a.blocks_to_swap)] if a.blocks_to_swap else []

    steps = []
    if not a.skip_cache:
        steps.append(("cache latents", [py, str(scripts / "krea2_cache_latents.py"),
                                        "--dataset_config", cfgp,
                                        "--vae", models["vae"], "--skip_existing"]))
        steps.append(("cache text", [py, str(scripts / "krea2_cache_text.py"),
                                     "--dataset_config", cfgp,
                                     "--text_encoder", models["text_encoder"],
                                     "--skip_existing"]))
    train = [py, str(scripts / "krea2_train.py"),
             "--dataset_config", cfgp,
             "--dit", models["dit"], "--vae", models["vae"],
             "--text_encoder", models["text_encoder"], "--turbo_dit", models["turbo_dit"],
             "--output_dir", out, "--output_name", DS_ID,
             "--network_dim", "16", "--network_alpha", "16",
             "--max_train_epochs", str(a.epochs),
             "--save_every_n_epochs", "1", "--save_state", "--keep_last_n_states", "2",
             "--seed", "42",
             "--adaptive_lr", "--adaptive_lr_min", "5e-5", "--adaptive_lr_max", "4e-4",
             "--log_per_image_loss", "--per_image_lr", "--auto_recaption",
             "--warmup_look_outliers", "--trigger_word", TRIGGER,
             "--sample_every_n_epochs", "1",
             "--sample_width", "1024", "--sample_height", "1024"] + quant + swap
    sp = HERE / "sample_prompts.txt"
    if sp.is_file():
        train += ["--sample_prompts", str(sp)]
    ref = HERE / "sample_ref.png"
    if ref.is_file():
        train += ["--sample_ref_image", str(ref)]
    steps.append(("train", train))

    for label, cmd in steps:
        print("")
        print("=== " + label + " ===")
        print(" ".join(('"' + c + '"') if " " in c else c for c in cmd))
        if a.dry_run:
            continue
        # cwd=fiz and PYTHONPATH=<fizgig>/src: the scripts do `from fizgig.krea2 import ...`,
        # which only resolves from the checkout, never from this zip's folder.
        env = dict(os.environ, PYTHONPATH=str(fiz / "src"))
        r = subprocess.run(cmd, cwd=str(fiz), env=env)
        if r.returncode != 0:
            die(label + " exited " + str(r.returncode) + " - stopping before the next step")
    if not a.dry_run:
        print("")
        print("Done.  LoRA + checkpoints in: " + out)


if __name__ == "__main__":
    main()
'''


def _fizgig_bat(ds: dict) -> str:
    """Double-clickable Windows wrapper.  One line to edit."""
    return (
        "@echo off\n"
        "REM Train " + str(ds.get("id")) + " on Fizgig.\n"
        "REM  1. set FIZGIG below to your Fizgig folder   2. double-click this file\n"
        "setlocal\n"
        'set "FIZGIG=C:\\Fizgig"\n'
        'cd /d "%~dp0"\n'
        'if not exist "%FIZGIG%\\lora_trainer_gui.py" (\n'
        "  echo Edit this file and set FIZGIG to the folder containing lora_trainer_gui.py\n"
        "  pause\n"
        "  exit /b 2\n"
        ")\n"
        "REM Fizgig's own venv python, so torch/CUDA are the ones it was installed with.\n"
        'set "PY=%FIZGIG%\\venv\\Scripts\\python.exe"\n'
        'if not exist "%PY%" set "PY=python"\n'
        '"%PY%" "%~dp0fizgig_run.py" --fizgig "%FIZGIG%" --python "%PY%" %*\n'
        "pause\n")


def _fizgig_sh(ds: dict) -> str:
    """Linux/RunPod wrapper — same runner, FIZGIG from the environment."""
    return (
        "#!/usr/bin/env bash\n"
        "# Train " + str(ds.get("id")) + " on Fizgig.\n"
        "#   FIZGIG=/workspace/Fizgig ./train_krea2_fizgig.sh\n"
        "set -euo pipefail\n"
        'cd "$(dirname "$0")"\n'
        'FIZGIG="${FIZGIG:-$HOME/Fizgig}"\n'
        '[ -f "$FIZGIG/lora_trainer_gui.py" ] || {\n'
        '  echo "Set FIZGIG to the folder containing lora_trainer_gui.py"; exit 2; }\n'
        'PY="$FIZGIG/venv/bin/python"; [ -x "$PY" ] || PY="python3"\n'
        '"$PY" ./fizgig_run.py --fizgig "$FIZGIG" --python "$PY" "$@"\n')

